// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for compilation

package grpc

// Message types
type GetPolicyRequest struct {
	PolicyId string
	AgentId  string
}

type ListPoliciesRequest struct {
	Limit  int32
	Offset int32
}

type CreatePolicyRequest struct {
	Name        string
	Description string
	Rules       string
	Priority    int32
	Enabled     bool
}

type UpdatePolicyRequest struct {
	Id          string
	Name        string
	Description string
	Rules       string
	Priority    int32
	Enabled     bool
}

type DeletePolicyRequest struct {
	Id string
}

type DeletePolicyResponse struct {
	Success bool
}

type Policy struct {
	Id          string
	Name        string
	Description string
	Rules       string
	Priority    int32
	Enabled     bool
	CreatedAt   string
	UpdatedAt   string
}

type PolicySummary struct {
	Id        string
	Name      string
	CreatedAt string
}

type ListPoliciesResponse struct {
	Policies []*PolicySummary
}

type Event struct {
	AgentId     string
	EventType   string
	Operation   string
	SourcePath  string
	Destination string
	Application string
	UserId      string
	Data        string
	Severity    string
	ActionTaken string
	PolicyId    string
	RuleId      string
	Timestamp   int64
}

type StreamEventsResponse struct {
	Success bool
	Message string
}

type RegisterEndpointRequest struct {
	AgentId     string
	Hostname    string
	IpAddress   string
	OsVersion   string
	AgentVersion string
}

type GetEndpointRequest struct {
	AgentId string
}

type ListEndpointsRequest struct {
	Limit  int32
	Offset int32
}

type UpdateLastSeenRequest struct {
	AgentId string
}

type UpdateLastSeenResponse struct {
	Success bool
}

type Endpoint struct {
	Id           string
	AgentId      string
	Hostname     string
	IpAddress    string
	OsVersion    string
	AgentVersion string
	LastSeen     string
	CreatedAt    string
	Status       string
}

type ListEndpointsResponse struct {
	Endpoints []*Endpoint
}
