package api

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

// GetManifest returns the agent artifact manifest (name, arch, size, sha256)
// generated by the build-and-package-agent.ps1 script. It is read from
// static/artifacts/manifest.json so the backend always serves exactly what the
// build script produced. The bootstrap installer picks the artifact matching
// its architecture and verifies the SHA256 + size before extraction.
func GetManifest(w http.ResponseWriter, r *http.Request) {
	manifestPath, err := resolveArtifactsPath("manifest.json")
	if err != nil {
		log.Printf("[INSTALL] Manifest missing: %v", err)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{
			"error":   "MANIFEST_MISSING",
			"message": "Agent artifact manifest is not available. Run the build script.",
		})
		return
	}

	manifestBytes, err := os.ReadFile(manifestPath)
	if err != nil {
		log.Printf("[INSTALL] Failed to read manifest %s: %v", manifestPath, err)
		http.Error(w, "failed to read agent manifest", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Write(manifestBytes)
}

// DownloadArtifact serves a named agent artifact (e.g. PritrakDLP-Agent-1.0.0-x64.zip)
// from the static/artifacts/ directory. The filename is taken from the URL path
// suffix and strictly validated to prevent path traversal: only alphanumeric
// characters, hyphens, and dots are allowed, and any traversal sequence (..,
// backslash, or forward slash) is rejected outright.
func DownloadArtifact(w http.ResponseWriter, r *http.Request) {
	name := strings.TrimPrefix(r.URL.Path, "/api/v1/install/artifacts/")

	if name == "" || strings.Contains(name, "..") || strings.ContainsAny(name, "\\/") {
		http.Error(w, "invalid artifact name", http.StatusBadRequest)
		return
	}
	if !isValidArtifactName(name) {
		http.Error(w, "invalid artifact name", http.StatusBadRequest)
		return
	}

	artifactPath, err := resolveArtifactsPath(name)
	if err != nil {
		log.Printf("[INSTALL] Artifact %q requested but missing: %v", name, err)
		http.Error(w, "artifact not found", http.StatusNotFound)
		return
	}

	http.ServeFile(w, r, artifactPath)
}

// isValidArtifactName reports whether a filename consists only of alphanumeric
// characters, hyphens, and dots (no path separators or traversal sequences).
func isValidArtifactName(name string) bool {
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '.':
		default:
			return false
		}
	}
	return true
}

// GetBootstrapScript serves the single-line bootstrap installer used by the
// enterprise deployment flow (irm http://<server>/api/v1/install/bootstrap.ps1 | iex).
// The ?server= query parameter is injected into the $Server variable so the
// script targets the correct backend; it defaults to localhost when omitted.
func GetBootstrapScript(w http.ResponseWriter, r *http.Request) {
	server := r.URL.Query().Get("server")
	if server == "" {
		server = "http://localhost:8080"
	}

	scriptPath := filepath.Join("internal", "api", "bootstrap.ps1")
	scriptBytes, err := os.ReadFile(scriptPath)
	if err != nil {
		log.Printf("[INSTALL] Bootstrap script missing: %v", err)
		http.Error(w, "Bootstrap script not found", http.StatusInternalServerError)
		return
	}

	bootstrap := strings.Replace(string(scriptBytes), "{{SERVER_URL}}", server, 1)

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(bootstrap))
}

// resolveArtifactsPath locates a file in the static/artifacts/ directory,
// trying several candidate roots so the server works regardless of the current
// working directory when launched.
func resolveArtifactsPath(name string) (string, error) {
	candidates := []string{
		filepath.Join("static", "artifacts", name),
		filepath.Join("..", "static", "artifacts", name),
		filepath.Join("backend", "static", "artifacts", name),
	}
	for _, candidate := range candidates {
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("static/artifacts/%s not found", name)
}

// GetAgentInstaller serves the PowerShell agent installer script
func GetAgentInstaller(w http.ResponseWriter, r *http.Request) {
	// Get server IP from request host
	serverHost := r.Host
	serverIP := strings.Split(serverHost, ":")[0]

	// Read the PowerShell template file
	scriptPath := filepath.Join("internal", "api", "agent-installer.ps1")
	scriptBytes, err := os.ReadFile(scriptPath)
	if err != nil {
		http.Error(w, "Installer script not found", http.StatusInternalServerError)
		return
	}

	// Replace the placeholder with actual server IP
	installerScript := strings.Replace(string(scriptBytes), "REPLACE_SERVER_IP", serverIP, 1)

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=agent.ps1")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(installerScript))
}

// GetAgentDLPv2 serves the DLP v2 agent script with file blocking capabilities
func GetAgentDLPv2(w http.ResponseWriter, r *http.Request) {
	scriptPath := filepath.Join("internal", "api", "agent-dlp-v2.ps1")
	scriptBytes, err := os.ReadFile(scriptPath)
	if err != nil {
		http.Error(w, "DLP v2 agent script not found", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=agent-dlp-v2.ps1")
	w.WriteHeader(http.StatusOK)
	w.Write(scriptBytes)
}

// GetAgentDLPv3Enterprise serves the Enterprise DLP v3 agent with TRUE file blocking
func GetAgentDLPv3Enterprise(w http.ResponseWriter, r *http.Request) {
	// Get server IP from request host
	serverHost := r.Host
	serverIP := strings.Split(serverHost, ":")[0]

	scriptPath := filepath.Join("internal", "api", "agent-dlp-v3-enterprise.ps1")
	scriptBytes, err := os.ReadFile(scriptPath)
	if err != nil {
		http.Error(w, "DLP v3 Enterprise agent script not found", http.StatusInternalServerError)
		return
	}

	// Replace the server IP placeholder
	agentScript := strings.Replace(string(scriptBytes), "YOURSERVERIP", serverIP, -1)

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=agent-dlp-v3-enterprise.ps1")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(agentScript))
}

// GetAgentInstallerV3 serves the v3 Enterprise installer script
func GetAgentInstallerV3(w http.ResponseWriter, r *http.Request) {
	// Get server IP from request host
	serverHost := r.Host
	serverIP := strings.Split(serverHost, ":")[0]

	// Read the PowerShell template file
	scriptPath := filepath.Join("internal", "api", "agent-installer-v3.ps1")
	scriptBytes, err := os.ReadFile(scriptPath)
	if err != nil {
		http.Error(w, "V3 Installer script not found", http.StatusInternalServerError)
		return
	}

	// Replace the placeholder with actual server IP
	installerScript := strings.Replace(string(scriptBytes), "REPLACE_SERVER_IP", serverIP, 1)

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=agent-v3.ps1")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(installerScript))
}

// GetAgentKernelInstaller serves the kernel-mode agent installer
// Usage: irm http://SERVER:8080/api/install/agent-kernel.ps1 | iex
func GetAgentKernelInstaller(w http.ResponseWriter, r *http.Request) {
	// Get server IP from request host
	serverHost := r.Host
	serverIP := strings.Split(serverHost, ":")[0]

	// Read the kernel installer script
	scriptPath := filepath.Join("internal", "api", "agent-kernel-installer.ps1")
	scriptBytes, err := os.ReadFile(scriptPath)
	if err != nil {
		http.Error(w, "Kernel installer script not found", http.StatusInternalServerError)
		return
	}

	// Replace server IP placeholder
	installerScript := strings.Replace(string(scriptBytes), "YOURSERVERIP", serverIP, -1)

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=agent-kernel.ps1")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(installerScript))
}

// GetMinifilterDriver serves the minifilter driver binary
func GetMinifilterDriver(w http.ResponseWriter, r *http.Request) {
	// Look for driver in multiple locations
	possiblePaths := []string{
		filepath.Join("agent", "kernel", "minifilter", "x64", "Release", "PritrakDLPFilter.sys"),
		filepath.Join("..", "agent", "kernel", "minifilter", "x64", "Release", "PritrakDLPFilter.sys"),
		filepath.Join("drivers", "PritrakDLPFilter.sys"),
	}

	var driverBytes []byte
	var err error
	for _, driverPath := range possiblePaths {
		driverBytes, err = os.ReadFile(driverPath)
		if err == nil {
			break
		}
	}

	if err != nil {
		http.Error(w, "Minifilter driver not found. Please build the driver first.", http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", "attachment; filename=PritrakDLPFilter.sys")
	w.Header().Set("Content-Length", fmt.Sprintf("%d", len(driverBytes)))
	w.WriteHeader(http.StatusOK)
	w.Write(driverBytes)
}

// GetWfpDriver serves the WFP network driver binary
func GetWfpDriver(w http.ResponseWriter, r *http.Request) {
	// Look for driver in multiple locations
	possiblePaths := []string{
		filepath.Join("agent", "kernel", "wfp", "x64", "Release", "PritrakDLPNetwork.sys"),
		filepath.Join("..", "agent", "kernel", "wfp", "x64", "Release", "PritrakDLPNetwork.sys"),
		filepath.Join("drivers", "PritrakDLPNetwork.sys"),
	}

	var driverBytes []byte
	var err error
	for _, driverPath := range possiblePaths {
		driverBytes, err = os.ReadFile(driverPath)
		if err == nil {
			break
		}
	}

	if err != nil {
		http.Error(w, "WFP driver not found. Please build the driver first.", http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Header().Set("Content-Disposition", "attachment; filename=PritrakDLPNetwork.sys")
	w.Header().Set("Content-Length", fmt.Sprintf("%d", len(driverBytes)))
	w.WriteHeader(http.StatusOK)
	w.Write(driverBytes)
}