-- Classification Rules System (V3.0)
-- Enables admins to create custom rules for file classification

CREATE TABLE IF NOT EXISTS classification_rules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    enabled BOOLEAN DEFAULT TRUE,
    priority INTEGER DEFAULT 100,
    
    -- Condition (what triggers the rule)
    condition_field TEXT NOT NULL,
    condition_operator TEXT NOT NULL,
    condition_value TEXT NOT NULL,
    
    -- Action (what happens when rule triggers)
    action_type TEXT NOT NULL DEFAULT 'classify_as',
    action_classification TEXT,
    
    -- Metadata
    created_by TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_system BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_rules_priority ON classification_rules(priority, enabled);
CREATE INDEX IF NOT EXISTS idx_rules_enabled ON classification_rules(enabled);

CREATE TABLE IF NOT EXISTS rule_audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id INTEGER NOT NULL,
    file_path TEXT NOT NULL,
    old_classification TEXT,
    new_classification TEXT,
    triggered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(rule_id) REFERENCES classification_rules(id)
);

CREATE INDEX IF NOT EXISTS idx_audit_log_rule_id ON rule_audit_log(rule_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_file_path ON rule_audit_log(file_path);

-- Insert default system rules (examples)
INSERT INTO classification_rules 
(name, description, enabled, priority, condition_field, condition_operator, condition_value, action_type, action_classification, is_system, created_by)
VALUES 
('Source Code Files', 'Automatically classify source code as INTERNAL', TRUE, 50, 'file_extension', 'in_list', '.cpp,.py,.js,.java,.ts,.go,.rs', 'classify_as', 'INTERNAL', TRUE, 'system'),
('Password Files', 'Automatically classify password files as RESTRICTED', TRUE, 10, 'keyword', 'matches_regex', '^.*\.(key|pem|p12|pfx|ppk|env)$', 'classify_as', 'RESTRICTED', TRUE, 'system'),
('Database Backups', 'Automatically classify database backups as RESTRICTED', TRUE, 20, 'file_extension', 'in_list', '.sql,.sql.bak,.backup', 'classify_as', 'RESTRICTED', TRUE, 'system')
ON CONFLICT (name) DO NOTHING;
